name: Exécution des tests unitaires

# Définition de l'évènement déclencheur
on:
  push:
    branches:
      - doscod
# Configuration du jobs
jobs:
  tests-unitaires:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configuration de Node.js
      uses: actions/setup-node@v2
      with:
        with:
          node-version: '18'

    - name: Installation des dépendances
      run: npm install

    - name: Exécution du test
      run: npm test
      working-directory: test
