name: Exécution des tests unitaires

# Définition de l'évènement déclencheur
on:
  push:
    branches:
      - doscod
# Configuration du jobs
jobs:
  tests-unitaires:
    runs-on: ubuntu-latest

    # Configuration de la matrix
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configuration de Node.js
      uses: actions/setup-node@v2
      with:
        with:
          node-version: ${{ matrix.node-version }}

    - name: Installation des dépendances
      run: npm install

    - name: Exécution du test
      run: npm test
      working-directory: test
